name: madebylouie
favicon: null
layout_spectrum: 0.8014
typography_spectrum: 0.46501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3c8c6'
    - '#ada8ac'
    - '#868686'
    - '#261c1a'
    - '#4d4442'
  brandStrength: 0
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
