name: madebylouie
favicon: null
layout_spectrum: 0.390997446840629
typography_spectrum: 0.6287809547502548
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6035133565310389
  lightness: 0.9375060638412833
  saturation: 0.10577327315695584
  rhythmicContrast: 0.789520962163806
purpose: []
